import type { Lang } from '../config';

export const LANG_SUFFIX_RE = /\.(zh-hans|zh-hant)$/;

/**
 * Slugify one path segment into an entry id segment.
 * All existing filenames match `[a-z0-9-]+` and pass through unchanged, which
 * keeps every current URL identical to the previous glob-based ids.
 */
export function slugifySegment(segment: string): string {
  if (/^[a-z0-9-]+$/.test(segment)) return segment;
  return segment
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** Convert a file path (relative to the content base) into a collection id. */
export function slugFromRelPath(relPath: string): string {
  const posixPath = relPath.split(/[\\/]/).join('/');
  const dotIndex = posixPath.lastIndexOf('.');
  const withoutExt = dotIndex > 0 ? posixPath.slice(0, dotIndex) : posixPath;
  return withoutExt
    .split('/')
    .map((segment) => slugifySegment(segment))
    .join('/')
    .replace(/\/index$/, '');
}

export interface RawEntryMeta {
  /** glob-style id of the raw file (e.g. `beijing`, `atcoder/abc299f`) */
  id: string;
  lang: Lang;
  /** `true` marks files that were generated by the old OpenCC script; they are stale artifacts */
  opencc?: boolean;
}

export interface ConvertSpec {
  /** store id of the entry to emit (e.g. `beijing.zh-hant`) */
  id: string;
  /** id of the raw entry that supplies the content */
  sourceId: string;
  lang: Lang;
}

export interface LangPlan {
  /** raw entry ids that should be stored as-is */
  keep: Set<string>;
  /** entries to derive from a source via OpenCC */
  converts: ConvertSpec[];
  /** lang-suffixed entries shadowed by their base file (duplicate language) */
  shadowed: string[];
}

/** Strip the `.zh-hans` / `.zh-hant` suffix from an entry id. */
export function baseIdOf(id: string): string {
  return id.replace(LANG_SUFFIX_RE, '');
}

/**
 * Decide which entries to emit for a set of raw files:
 * - `opencc: true` files are stale generated artifacts and are ignored;
 * - for each base id (id without a `.zh-hans`/`.zh-hant` suffix), every locale
 *   gets exactly one entry: the explicit file when one declares that locale
 *   (the base file wins over a lang-suffixed duplicate), otherwise a converted
 *   copy derived from the group's source file.
 */
export function planLangEntries(
  raw: RawEntryMeta[],
  locales: readonly Lang[],
): LangPlan {
  const sources = raw.filter((entry) => entry.opencc !== true);
  const groups = new Map<string, RawEntryMeta[]>();

  for (const entry of sources) {
    const base = baseIdOf(entry.id);
    const group = groups.get(base);
    if (group) group.push(entry);
    else groups.set(base, [entry]);
  }

  const keep = new Set<string>();
  const converts: ConvertSpec[] = [];
  const shadowed: string[] = [];

  for (const [base, group] of groups) {
    const baseFile = group.find((entry) => entry.id === base) ?? group[0];

    for (const lang of locales) {
      const explicit = group.filter((entry) => entry.lang === lang);
      if (explicit.length === 0) {
        converts.push({
          id: `${base}.${lang}`,
          sourceId: baseFile.id,
          lang,
        });
        continue;
      }

      const chosen = explicit.find((entry) => entry.id === base) ?? explicit[0];
      keep.add(chosen.id);
      for (const entry of explicit) {
        if (entry.id !== chosen.id) shadowed.push(entry.id);
      }
    }
  }

  return { keep, converts, shadowed };
}
